blank_issues_enabled: false
contact_links:
  - name: Feature request
    url: https://github.com/the-it-dept/node-isp-community/discussions
    about: 'For ideas or feature requests, start a new discussion'
  - name: Security vulnerabilities
    url: mailto:support@theitdept.au
    about: If you want to report a security issue, please contact our support.
  - name: The IT Dept Pty Ltd
    url: https://theitdept.au/
    about: Learn more about The IT Dept Pty Ltd
